mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/nodejs',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'cargomedia/janus',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/janus'

mod 'cargomedia/chromium',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/chromium'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/daemon',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/daemon'

mod 'cargomedia/xvfb',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/xvfb'

mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/env',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/env'
